#!/usr/bin/env python3
"""Build the Springer media-enhancement manifest from manuscript links and registry entries."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / "compliance" / "media-enhancements.yml"
TOOL_DIR = ROOT / "tools" / "registry"
URL_RE = re.compile(r'https?://[^\s)>\]}`"]+')

MANUSCRIPT_UNITS = {
    "front": ROOT / "book" / "index.qmd",
    **{
        f"ch{number:02d}": next(
            (ROOT / "book" / "chapters").glob(f"{number:02d}-*/*.qmd")
        )
        for number in range(1, 12)
    },
    # Appendices are discovered rather than hardcoded. The previous map named
    # appendix-a-bootstrapping and appendix-b-design-loop-card, both removed in
    # 356e66f, which made this script raise FileNotFoundError and left the
    # manifest test permanently red. Globbing keeps it correct across renames.
    **{
        f"app{path.parent.name.split('-')[1].upper()}": path
        for path in sorted((ROOT / "book" / "appendices").glob("apdx-*/*.qmd"))
    },
}

PROJECT_OWNER = "Vijay Janapa Reddi / Harvard Edge project"

COMPANION_METADATA: dict[str, dict[str, str]] = {
    "https://github.com/harvard-edge/arch2/tree/f5516e52e66243c2d753191e350a5cfac56c83af/labs/examples/ai_systolic_array_study": {
        "purpose": "frozen study package",
        "owner": PROJECT_OWNER,
        "nature": "example",
        "description": "Commit-pinned package for the retained systolic-array study, including its preregistration, provenance, configurations, and results.",
    },
    "https://github.com/harvard-edge/arch2/blob/f5516e52e66243c2d753191e350a5cfac56c83af/labs/examples/ai_systolic_array_study/context/pre_registration.yaml": {
        "purpose": "frozen study preregistration",
        "owner": PROJECT_OWNER,
        "nature": "record",
        "description": "Commit-pinned preregistration that fixes the retained study's question, comparison, and interpretation rules.",
    },
    "https://github.com/harvard-edge/arch2/blob/f5516e52e66243c2d753191e350a5cfac56c83af/labs/examples/ai_systolic_array_study/recorded/model/provenance.json": {
        "purpose": "retained model provenance",
        "owner": PROJECT_OWNER,
        "nature": "record",
        "description": "Commit-pinned provenance for the model-assisted proposal step in the retained systolic-array study.",
    },
    "https://github.com/harvard-edge/arch2/blob/f5516e52e66243c2d753191e350a5cfac56c83af/labs/examples/ai_systolic_array_study/recorded/reference/execution_provenance.json": {
        "purpose": "retained execution provenance",
        "owner": PROJECT_OWNER,
        "nature": "record",
        "description": "Commit-pinned environment and tool provenance for the retained SCALE-Sim executions.",
    },
    "https://github.com/harvard-edge/arch2/blob/f5516e52e66243c2d753191e350a5cfac56c83af/labs/examples/ai_systolic_array_study/recorded/reference/study_results.json": {
        "purpose": "retained study results",
        "owner": PROJECT_OWNER,
        "nature": "data",
        "description": "Commit-pinned machine-readable outcomes for the retained systolic-array comparison and mechanism test.",
    },
    "https://github.com/harvard-edge/arch2/blob/f5516e52e66243c2d753191e350a5cfac56c83af/labs/examples/ai_systolic_array_study/recorded/reference/runs/probe_transposed_16x64/scalesim-results/probe_transposed_16x64/BANDWIDTH_REPORT.csv": {
        "purpose": "retained simulator bandwidth report",
        "owner": PROJECT_OWNER,
        "nature": "data",
        "description": "Commit-pinned SCALE-Sim bandwidth output used to document an unresolved simulator-semantics question.",
    },
    # start.html removed 2026-07-25: it was referenced only by
    # appendix-a-bootstrapping, deleted in 356e66f. No manuscript text points at
    # it and the page has no verifiable source in www/, so it is not shipped as a
    # companion link. Restore this entry together with any text that links it.
    # Pruned 2026-07-19: six tool/lab/repo links formerly surfaced only by the
    # refactored-out appendix-c-architecture-20-resources; no longer present in the book.
}

HEADER = """# Generated by .github/scripts/build_media_enhancements.py.
# Edit the direct-link metadata in that script or the source files in tools/registry/.
# Owner identifies the credited project steward or institution for delivery routing;
# it is not a determination of copyright ownership.
# Existing external URLs last checked: 2026-07-14; release-local assets are
# validated by the publication workflow.
"""


def direct_links() -> dict[str, list[str]]:
    links: dict[str, list[str]] = {}
    for chapter, path in MANUSCRIPT_UNITS.items():
        text = path.read_text(encoding="utf-8")
        for match in URL_RE.findall(text):
            url = match.rstrip(".,;:")
            links.setdefault(url, []).append(chapter)
    return {url: sorted(set(chapters)) for url, chapters in links.items()}


def companion_entries() -> list[dict[str, Any]]:
    links = direct_links()
    unknown = sorted(set(links) - set(COMPANION_METADATA))
    stale = sorted(set(COMPANION_METADATA) - set(links))
    if unknown or stale:
        details: list[str] = []
        if unknown:
            details.append(f"missing metadata for direct links: {unknown}")
        if stale:
            details.append(f"metadata no longer used by manuscript: {stale}")
        raise ValueError("; ".join(details))

    entries: list[dict[str, Any]] = []
    for url in sorted(links):
        metadata = COMPANION_METADATA[url]
        entries.append(
            {
                "url": url,
                "purpose": metadata["purpose"],
                "chapters": links[url],
                "owner": metadata["owner"],
                "nature": metadata["nature"],
                "description": metadata["description"],
                "source": "direct manuscript link",
            }
        )
    return entries


def registry_entries() -> list[dict[str, Any]]:
    entries: list[dict[str, Any]] = []
    for path in sorted(TOOL_DIR.glob("*.yml")):
        item = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        if not isinstance(item, dict):
            raise ValueError(f"{path}: expected a mapping")
        missing = [
            field
            for field in ("title", "url", "artifact_type", "description", "institution")
            if not item.get(field)
        ]
        if missing:
            raise ValueError(f"{path}: missing delivery fields {missing}")
        entry: dict[str, Any] = {
            "url": item["url"],
            "purpose": f"living registry entry for {item['title']}",
            # sourced from the tool registry (tools/registry/), not a manuscript unit;
            # the former appendix-c-architecture-20-resources that surfaced these was refactored out.
            "chapters": ["tool-registry"],
            "owner": item["institution"],
            "nature": str(item["artifact_type"]).lower(),
            "description": item["description"],
            "source": str(path.relative_to(ROOT)),
        }
        if item.get("authors"):
            entry["credits"] = item["authors"]
        if item.get("last_verified"):
            entry["last_verified"] = item["last_verified"]
        entries.append(entry)
    return sorted(entries, key=lambda entry: (entry["purpose"].lower(), entry["url"]))


def rendered_manifest() -> str:
    entries = companion_entries() + registry_entries()
    urls = [entry["url"] for entry in entries]
    duplicates = sorted({url for url in urls if urls.count(url) > 1})
    if duplicates:
        raise ValueError(f"duplicate manifest URLs: {duplicates}")
    body = yaml.safe_dump(
        {"media_enhancements": entries},
        sort_keys=False,
        allow_unicode=True,
        width=100,
    )
    return HEADER + body


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check", action="store_true", help="fail if the checked-in manifest is stale"
    )
    args = parser.parse_args()
    rendered = rendered_manifest()
    if args.check:
        actual = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if actual != rendered:
            print(f"{OUTPUT.relative_to(ROOT)} is stale", file=sys.stderr)
            return 1
        print(f"{OUTPUT.relative_to(ROOT)} is current")
        return 0
    OUTPUT.write_text(rendered, encoding="utf-8")
    count = len(yaml.safe_load(rendered)["media_enhancements"])
    print(f"Built {OUTPUT.relative_to(ROOT)} with {count} entries.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
