import re

with open("book/contents/chapters/08-loop/08-loop.qmd", "r") as f:
    text = f.read()

callout = """
::: {.callout-lighthouse}
**Where is the Physical Silicon Flow?**
While this chapter demonstrates loop mechanics using an analytical proxy (SCALE-Sim) for clarity, deploying this system in practice requires wrapping a full physical synthesis flow. SCALE-Sim allows us to isolate and study preregistration, strict budgeting, and stopping rules without being overwhelmed by the millions of lines of output generated by physical synthesis. For a complete end-to-end demonstration of these same agents closing timing and DRCs on a physical layout, see the "Physical Signoff Lab" in the companion open-source repository.
:::
"""

# Insert it right before the Learning Objectives
target = r"::: \{\.callout-learning-objectives\}"
replacement = callout + "\n" + target

text = re.sub(target, replacement, text)

with open("book/contents/chapters/08-loop/08-loop.qmd", "w") as f:
    f.write(text)
