-- filters/glossary.lua
-- Architecture 2.0 Quarto Filter: Injects semantic <abbr> tooltips for technical acronyms in HTML output.
-- Auto-generated by './arch2 generate glossary' from cli/arch2.py; do not edit directly.

local acronyms = {
  ["ABI"] = "application binary interface: The low-level binary interface between software programs and the operating system or hardware register state.",
  ["AIG"] = "and-inverter graph: A directed acyclic graph representation of a combinational logic circuit composed entirely of two-input AND nodes and logical inverters.",
  ["AMBA"] = "Arm Microcontroller Bus Architecture: An open-standard on-chip interconnect specification governing the connection and management of functional blocks in SoC designs.",
  ["AMX"] = "Advanced Matrix Extensions: A proprietary matrix acceleration instruction set extension developed by Intel for high-throughput tensor arithmetic.",
  ["ASIC"] = "application-specific integrated circuit: A custom-manufactured integrated circuit tailored to execute a specific computing workload with maximal energy and area efficiency.",
  ["AST"] = "abstract syntax tree: A tree representation of the abstract syntactic structure of source code, capturing grammatical hierarchy without formatting tokens.",
  ["AWC"] = "Autonomous Workflow Certified: A proposed artifact evaluation credential attesting to the computational reproducibility and explicit audit scope of an automated design workflow.",
  ["AXI"] = "Advanced eXtensible Interface: A high-performance, high-frequency, burst-based point-to-point interconnect protocol defined under the AMBA specification.",
  ["AXI5"] = "Advanced eXtensible Interface 5: The fifth-generation AMBA on-chip interconnect protocol standard providing high-performance point-to-point interface handshakes and atomic transactions.",
  ["BMC"] = "bounded model checking: A formal verification technique unrolling sequential circuit transitions up to a fixed depth $k$ and querying a SAT/SMT solver to prove or disprove properties.",
  ["BO"] = "Bayesian optimization: A sequential design strategy for global optimization of black-box objective functions using Gaussian process surrogate models and acquisition functions.",
  ["BSPDN"] = "backside power delivery network: A 3D semiconductor manufacturing technology that moves the power distribution metal grid to the backside of the silicon wafer to reduce IR-drop and routing congestion.",
  ["CAD"] = "computer-aided design: Software tools used by engineers to create, modify, analyze, and optimize physical hardware and circuit designs.",
  ["CDC"] = "clock-domain crossing: An interface where a signal generated in one clock domain is sampled in an asynchronous or unrelated clock domain, risking metastability.",
  ["CDFG"] = "control-data flow graph: A directed graph representation capturing both control branches and data dependencies within a computational block.",
  ["CEC"] = "combinational equivalence checking: A formal verification technique using SAT/BDD methods to prove that two combinational logic circuits produce identical Boolean outputs for all inputs.",
  ["CEGAR"] = "counterexample-guided abstraction refinement: An iterative formal verification algorithm that starts with a coarse abstract model and progressively refines it using concrete counterexamples.",
  ["CIRCT"] = "Circuit IR Compilers and Tools: An open-source, LLVM/MLIR-based hardware compiler infrastructure providing dialect-driven lowering from high-level abstractions to synthesizable RTL.",
  ["CNN"] = "convolutional neural network: A class of deep neural networks using spatial convolution kernels, widely used in computer vision and structured tensor representations.",
  ["CPU"] = "central processing unit: The primary general-purpose execution engine that sequences and executes instruction streams in a computer system.",
  ["CXL"] = "Compute Express Link: An open industry-standard cache-coherent interconnect protocol running over PCIe physical layers for high-speed CPU-to-device and CPU-to-memory expansion.",
  ["DDR"] = "double data rate: A memory bus protocol that transfers data on both the rising and falling edges of the clock cycle.",
  ["DEF"] = "Design Exchange Format: An open ASCII representation format for transferring physical layout, placement, and routing data between EDA physical design tools.",
  ["DMA"] = "direct memory access: A hardware feature allowing peripheral devices or accelerators to transfer data directly to and from main memory without processor intervention.",
  ["DNN"] = "deep neural network: An artificial neural network with multiple hidden layers between input and output capable of learning hierarchical feature representations.",
  ["DQN"] = "deep Q-network: A model-free reinforcement learning algorithm combining Q-learning with deep neural network function approximators.",
  ["DRC"] = "design rule check: Automated verification checking that a physical IC layout complies with the geometric constraints dictated by the semiconductor foundry's manufacturing process.",
  ["DSA"] = "domain-specific architecture: A customized processor or compute engine engineered specifically to maximize execution efficiency for a targeted family of workloads.",
  ["DSE"] = "design-space exploration: The systematic evaluation of architectural and microarchitectural parameters to identify Pareto-optimal trade-offs across power, performance, and area.",
  ["DVFS"] = "dynamic voltage and frequency scaling: A power management technique that dynamically adjusts operating voltage and clock frequency to balance performance against thermal dissipation.",
  ["ECE"] = "expected calibration error: A statistical metric measuring the difference between predicted model confidence probabilities and actual empirical accuracy.",
  ["ECO"] = "engineering change order: A formal modification process applied late in the design or physical layout cycle to fix bugs or timing violations with minimal disruption to the netlist.",
  ["EDA"] = "electronic design automation: The category of software tools, algorithms, and workflows used to design, simulate, verify, and physically layout electronic systems and semiconductors.",
  ["ESD"] = "electrostatic discharge: A sudden transient flow of electric current between charged bodies that requires on-chip protection structures to prevent physical dielectric breakdown.",
  ["EVM"] = "emergency voltage mitigation: Dynamic hardware circuitry that rapidly detects supply voltage droop and temporarily throttles clock frequency or compute activity.",
  ["FDIV"] = "floating-point division: A hardware arithmetic division unit, notably associated with the historic 1994 Pentium microprocessor verification defect.",
  ["FIFO"] = "first-in, first-out: A queue data structure or buffer hardware where the earliest stored data elements are retrieved first.",
  ["FIRRTL"] = "Flexible Intermediate Representation for RTL: An intermediate representation designed for hardware digital design and compiler passes in the Chisel and CIRCT ecosystems.",
  ["FP8"] = "8-bit floating-point: A low-precision floating-point arithmetic format standardized for high-throughput deep learning training and inference.",
  ["FPGA"] = "field-programmable gate array: A reconfigurable integrated circuit containing programmable logic blocks and routing channels configured post-fabrication.",
  ["FPS"] = "frames per second: A frame-rate unit for real-time rendering and perception pipelines, used to state a display or sensor deadline.",
  ["FSDB"] = "Fast Signal Database: A high-performance proprietary binary waveform database format widely used for storing simulation and emulation signal traces.",
  ["GAAFET"] = "gate-all-around field-effect transistor: An advanced transistor architecture where the gate material surrounds all sides of vertically stacked nanosheet or nanowire conduction channels.",
  ["GDDR5"] = "Graphics Double Data Rate 5: A high-bandwidth synchronous graphics random-access memory interface standard tailored for parallel data-intensive computing.",
  ["GDSII"] = "Graphic Database System II: The industry-standard binary format for representing integrated circuit planar geometric layout artwork transferred to foundries for photomask fabrication.",
  ["GEMM"] = "general matrix multiply: The canonical linear algebra compute kernel forming the computational core of deep neural network acceleration.",
  ["GNN"] = "graph neural network: A class of deep learning architectures operating directly on graph-structured data via message-passing between nodes and edges.",
  ["GPU"] = "graphics processing unit: A massively parallel processor optimized for high-throughput rasterization, linear algebra, and tensor operations.",
  ["HBM"] = "High Bandwidth Memory: A high-speed 3D-stacked DRAM memory architecture providing massive memory bandwidth through wide through-silicon via (TSV) interconnects.",
  ["HDL"] = "hardware description language: A specialized formal language (such as SystemVerilog or VHDL) used to model the structure, behavior, and timing of digital electronic circuits.",
  ["HELM"] = "Holistic Evaluation of Language Models: A standardized benchmark framework that systematically evaluates foundation language models across diverse capabilities, risks, and behavioral metrics.",
  ["HLS"] = "high-level synthesis: An automated compilation process transforming algorithmic descriptions into cycle-accurate register-transfer level hardware.",
  ["HPC"] = "high-performance computing: The practice of aggregating computing power to perform complex calculations at massively parallel scales.",
  ["IEEE"] = "Institute of Electrical and Electronics Engineers: The professional engineering organization responsible for international standards including SystemVerilog (1800), SystemC (1666), and UPF (1801).",
  ["INT4"] = "4-bit integer: A quantized integer numeric representation using 4 bits per weight or activation to minimize memory bandwidth and footprint in deep learning accelerators.",
  ["INT8"] = "8-bit integer: An integer data format using 8 bits of precision commonly deployed in quantized neural network inference accelerators.",
  ["IPC"] = "instructions per cycle: A standard microarchitectural throughput metric measuring the average number of instructions executed per clock cycle.",
  ["IR"] = "intermediate representation: A standardized internal data structure or code format used by compilers to represent program or hardware semantics between passes.",
  ["IR-drop"] = "voltage drop: The parasitic reduction in supply voltage across a power distribution network caused by current flow through resistive on-chip metal tracks.",
  ["ISA"] = "instruction set architecture: The abstract model and boundary defining instructions, registers, addressing modes, and memory consistency for a processor.",
  ["JIT"] = "just-in-time: A compilation strategy where intermediate representations or bytecode are compiled into native machine code dynamically during program execution.",
  ["KGD"] = "known-good die: A bare semiconductor die or chiplet that has been comprehensively tested and verified to meet functional and electrical specifications prior to multi-die package assembly.",
  ["KV"] = "key-value: A pair of tensors storing intermediate attention projections in transformer models, frequently cached across decoding steps.",
  ["LEF"] = "Library Exchange Format: An ASCII data format describing standard cell and macro pin geometries, routing layers, and obstruction boundaries for automated place-and-route tools.",
  ["LLM"] = "large language model: A deep neural network trained on vast text or code corpora, capable of autoregressive token generation for natural language reasoning and code synthesis.",
  ["LP"] = "low-power: A foundry process node or silicon design methodology optimized for minimal active switching and subthreshold leakage power.",
  ["LVS"] = "layout versus schematic: Verification confirming that drawn physical layout mask geometry matches the electrical connectivity of the synthesized netlist.",
  ["MCTS"] = "Monte Carlo tree search: A heuristic search algorithm for decision processes combining tree traversal with Monte Carlo rollouts to evaluate candidate actions.",
  ["MDP"] = "Markov decision process: A formal mathematical framework for modeling decision-making in discrete stochastic environments defined by states, actions, transition probabilities, and rewards.",
  ["MLIR"] = "Multi-Level Intermediate Representation: A modular compiler infrastructure within LLVM providing extensible dialects for domain-specific transformations and multi-stage hardware/software lowering.",
  ["MoE"] = "mixture of experts: A neural network architecture routing individual input tokens to specialized expert sub-networks to scale parameter capacity with constant compute.",
  ["MPW"] = "multi-project wafer: A shared semiconductor fabrication shuttle run combining multiple distinct customer designs onto common reticle masks to amortize tooling charges.",
  ["MSHR"] = "miss status holding register: A specialized hardware buffer in non-blocking caches tracking in-flight memory requests to allow cache lookups to continue during outstanding misses.",
  ["MTBF"] = "mean time between failures: The predicted elapsed time between inherent operational failures of a hardware system during normal operation.",
  ["NDA"] = "nondisclosure agreement: A confidential legal contract protecting proprietary process design kits, standard cell libraries, and foundry yield data from unauthorized disclosure.",
  ["NoC"] = "network-on-chip: An on-die packet-switched communication subsystem connecting processing elements, caches, and memory controllers.",
  ["NPU"] = "neural processing unit: A specialized hardware accelerator designed specifically for accelerating tensor operations and deep neural network workloads.",
  ["NRE"] = "non-recurring engineering: The one-time, upfront engineering and mask tooling costs required to design, verify, and fabricate a new chip design before mass production.",
  ["NUMA"] = "non-uniform memory access: A multiprocessing system architecture where memory access latency varies depending on the physical proximity of the memory module to the requesting processor core.",
  ["OCI"] = "Open Container Initiative: An open governance structure standardizing container image formats and execution runtime specifications for software isolation.",
  ["PDK"] = "process design kit: A collection of device models, design rules, standard-cell libraries, and verification decks supplied by a foundry for a specific fabrication process.",
  ["PDN"] = "power delivery network: The on-die, package, and board-level metal interconnect network distributing supply voltage and ground across all active circuitry.",
  ["PE"] = "processing element: An individual arithmetic compute node or execution unit within a systolic array or parallel accelerator matrix.",
  ["PMP"] = "Physical Memory Protection: A RISC-V architectural standard providing hardware-enforced memory isolation and access permissions for physical memory regions.",
  ["PPA"] = "power, performance, and area: The tripartite metric vector governing semiconductor optimization and architectural figure-of-merit evaluation.",
  ["PPO"] = "proximal policy optimization: A model-free policy gradient reinforcement learning algorithm using clipped surrogate objectives to maintain stable policy updates.",
  ["PRD"] = "product requirements document: A formal engineering document defining the functionality, performance targets, physical constraints, and delivery requirements for a hardware system.",
  ["PST"] = "power state table: A tabular specification within IEEE 1801 UPF describing valid combinations of power domain voltage states and operating modes.",
  ["PVT"] = "process, voltage, and temperature: The three primary operational variation axes evaluated during static timing and power signoff across fast/slow silicon corners.",
  ["RDC"] = "reset domain crossing: An asynchronous structural boundary where a signal originates in one reset domain and enters logic reset by an unrelated reset controller.",
  ["RISC"] = "reduced instruction set computer: A processor design philosophy based on simplified instructions that execute in a single cycle with load-store memory access.",
  ["RL"] = "reinforcement learning: A machine learning paradigm where an autonomous agent learns to optimize a policy by taking actions in an environment to maximize cumulative reward signals.",
  ["ROB"] = "reorder buffer: A circular FIFO buffer in out-of-order execution processors tracking in-flight speculative instructions to ensure in-order retirement and precise exceptions.",
  ["RTL"] = "register-transfer level: A digital design modeling abstraction describing synchronous signal and data transfers between hardware registers through combinational logic.",
  ["RVWMO"] = "RISC-V Weak Memory Ordering: The canonical hardware memory consistency model for the RISC-V architecture defining legal ordering for multithreaded loads, stores, and fences.",
  ["SDC"] = "Synopsys Design Constraints: The industry-standard Tcl-based timing and physical constraint format specifying clock frequencies, input/output delays, and multi-cycle false paths.",
  ["SEC"] = "sequential equivalence checking: A formal verification method that mathematically proves two digital sequential circuits have identical input-output behavior over all cycles.",
  ["SEU"] = "single-event upset: A soft error or radiation-induced state change in a microelectronic device caused by ionizing radiation.",
  ["SLSA"] = "Supply Chain Levels for Software Artifacts: A security framework defining machine-readable, cryptographically signed metadata attestations for build provenance and supply chain integrity.",
  ["SNM"] = "static noise margin: A circuit figure of merit measuring the maximum DC noise voltage an SRAM bitcell can tolerate without inadvertently flipping its stored logic state.",
  ["SoC"] = "system-on-chip: An integrated circuit consolidating an entire electronic or computing system onto a single semiconductor die.",
  ["SPEC"] = "Standard Performance Evaluation Corporation: A non-profit organization establishing standardized benchmark suites to measure computing system performance.",
  ["SRAM"] = "static random-access memory: Fast, volatile semiconductor memory using bistable latching circuitry used for on-chip caches and scratchpads.",
  ["STA"] = "static timing analysis: A deterministic verification method calculating circuit delays across all signal paths to verify setup and hold timing without dynamic simulation.",
  ["SVA"] = "SystemVerilog Assertions: A declarative language extension within IEEE 1800 SystemVerilog used to specify temporal and Boolean properties for formal verification and dynamic simulation.",
  ["TCM"] = "tightly coupled memory: Fast, deterministic on-chip static RAM mapped directly into the processor core's memory map with zero wait states.",
  ["TCO"] = "total cost of ownership: A financial estimate encompassing all direct and indirect capital expenditures and operational costs over the lifetime of a computing system.",
  ["TDP"] = "thermal design power: The maximum sustained power consumption that a cooling system is engineered to dissipate under worst-case operational workloads.",
  ["TLB"] = "translation lookaside buffer: A dedicated hardware cache that stores recent virtual-to-physical address translations to accelerate memory access.",
  ["TLM"] = "transaction-level model: A high-level abstraction for modeling digital systems where module communication is represented as abstract transactions rather than pin-level clock cycles.",
  ["TNS"] = "Total Negative Slack: The cumulative sum of all negative timing slacks across all violating endpoints in a design's static timing analysis graph.",
  ["TPU"] = "Tensor Processing Unit: A custom-developed application-specific integrated circuit engineered by Google specifically for accelerating machine learning training and inference workloads.",
  ["TSO"] = "Total Store Order: A hardware memory consistency model guaranteeing that store operations from a given thread appear in program order to all processors.",
  ["UCIe"] = "Universal Chiplet Interconnect Express: An open industry standard defining die-to-die physical, protocol, and software connectivity for 2.5D and 3D multi-chiplet integration.",
  ["UPF"] = "Unified Power Format: The standard declarative language (IEEE 1801) specifying power intent, power domains, isolation cells, level shifters, and power switches across physical synthesis.",
  ["VCD"] = "value change dump: An ASCII-based industry standard waveform file format capturing signal value transitions during digital logic simulation.",
  ["VLA"] = "vector-length-agnostic: A processor architecture or compiler property where software binaries dynamically adapt to any hardware vector register length without recompilation.",
  ["VLSI"] = "very-large-scale integration: The process of creating integrated circuits by combining millions or billions of MOS transistors onto a single silicon chip.",
  ["WSC"] = "warehouse-scale computing: Massive datacenter computing systems engineered as a unified, coordinated warehouse of compute nodes, storage, and networking.",
}

if not quarto.doc.is_format('html') then
  return {}
end

local function replace_inlines(inlines)
  local result = pandoc.Inlines({})
  for i, inline in ipairs(inlines) do
    if inline.t == 'Str' then
      local clean, punct = inline.text:match('^([%a%-%d]+)([%p]*)$')
      if clean and acronyms[clean] then
        local title = acronyms[clean]:gsub('"', '&quot;')
        local html = '<abbr class="arch2-abbr" title="' .. title .. '">' .. clean .. '</abbr>' .. punct
        table.insert(result, pandoc.RawInline('html', html))
      else
        table.insert(result, inline)
      end
    elseif inline.t == 'Link' or inline.t == 'Code' or inline.t == 'Math' or inline.t == 'RawInline' then
      table.insert(result, inline)
    elseif inline.content and type(inline.content) == 'table' then
      inline.content = replace_inlines(inline.content)
      table.insert(result, inline)
    else
      table.insert(result, inline)
    end
  end
  return result
end

function Para(el)
  el.content = replace_inlines(el.content)
  return el
end

function Plain(el)
  el.content = replace_inlines(el.content)
  return el
end
