project:
  type: website
  output-dir: ../_site

metadata-files:
  - ../_global/navbar.yml

website:
  title: "Architecture 2.0"
  site-url: "https://arch2.mlsysbook.ai"
  description: "Designing the Loops that Design the Chips"
  
format:
  html:
    theme: cosmo
    css: styles.css
