project:
  type: website
  output-dir: ../_site/tools

metadata-files:
  - ../_global/navbar.yml

website:
  title: "Architecture 2.0 Catalog"
  site-url: "https://arch2.mlsysbook.ai/tools"
  
format:
  html:
    theme: cosmo
