#!/usr/bin/env python3
"""Plot the measured OpenROAD placement-seed pilot for the observatory.

Replaces `eda_seed_dispersion_distribution`, which was drawn from
`eda_seed_dispersion_qor_lottery.csv`, a file generated by `_gaussian_noise()`.
Every value here comes from `openroad_gcd_placement_seed_pilot.csv`: 20 runs of
GCD on Nangate45 through a digest-pinned OpenROAD container, one floorplan hash
across all runs, 20 distinct GPL_RANDOM_SEED values, placement stage only.
"""
from __future__ import annotations
import csv, statistics as st, sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
sys.path.insert(0, str(ROOT / "book"))

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from _python.plots import COLORS, apply_style

SRC = HERE / "openroad_gcd_placement_seed_pilot.csv"
OUT = [HERE, ROOT / "www" / "images" / "observatory"]


def main():
    rows = [r for r in csv.DictReader(open(SRC)) if r["status"] == "pass"]
    rows.sort(key=lambda r: int(r["seed"]))
    seeds = [int(r["seed"]) for r in rows]
    area = [float(r["detailedplace_instance_area_um2"]) for r in rows]
    wns = [float(r["detailedplace_setup_wns_ns"]) for r in rows]

    def dev(v):
        m = st.median(v)
        return [(x - m) / abs(m) * 100 for x in v], m

    ad, am = dev(area)
    wd, wm = dev(wns)
    asp = (max(area) - min(area)) / abs(am) * 100
    wsp = (max(wns) - min(wns)) / abs(wm) * 100

    apply_style()
    fig, ax = plt.subplots(figsize=(6.6, 2.5))
    ax.axhline(0, color=COLORS["muted"], lw=0.7, zorder=2)
    ax.plot(
        seeds,
        ad,
        color=COLORS["evidence"],
        lw=1.4,
        marker="o",
        ms=3.2,
        mec="white",
        mew=0.6,
        zorder=5,
        label=f"Instance area  (spread {asp:.2f}%)",
    )
    ax.plot(
        seeds,
        wd,
        color=COLORS["constraints"],
        lw=1.8,
        marker="D",
        ms=3.4,
        mec="white",
        mew=0.6,
        zorder=6,
        label=f"Setup slack, WNS  (spread {wsp:.2f}%)",
    )
    ax.set_xticks(seeds[::2])
    ax.set_xlabel("Global placement seed (GPL_RANDOM_SEED)")
    ax.set_ylabel("Deviation from median (%)")
    for s in ("top", "right"):
        ax.spines[s].set_visible(False)
    ax.grid(axis="y", color=COLORS["grid"], lw=0.5)
    ax.set_axisbelow(True)
    ax.tick_params(length=0)
    ax.legend(
        loc="upper center",
        bbox_to_anchor=(0.5, -0.28),
        ncol=2,
        frameon=False,
        fontsize=6.0,
    )
    fig.tight_layout()
    for d in OUT:
        d.mkdir(parents=True, exist_ok=True)
        for ext in ("png", "pdf", "svg"):
            fig.savefig(
                d / f"openroad_gcd_placement_seed_pilot.{ext}",
                dpi=300,
                bbox_inches="tight",
            )
    plt.close(fig)
    print(
        f"area spread {asp:.2f}%  ·  slack spread {wsp:.2f}%  ·  "
        f"ratio {wsp/asp:.1f}x"
    )
    print(
        "wrote openroad_gcd_placement_seed_pilot.{png,pdf,svg} to",
        ", ".join(str(d) for d in OUT),
    )


if __name__ == "__main__":
    main()
